#!/bin/sh

echo "Choosing a random wallpaper...."
wall=$(find /home/laith/pix -type f | shuf -n 1)
echo "Setting up wallpaper...."
xwallpaper --zoom $wall
echo "Generating pywal color schemes...."
wal -i $wall
sed -i 'N;$!P;D' $HOME//.cache/wal/colors-wal-dwm.h
echo "Recompiling dwm with new colors...."
(cd $HOME/dwm && sudo make clean install)
echo "^_^ Restart for new Look!"
